# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-24 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160924_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='ik',
            name='miniature',
            field=models.ImageField(default=None, upload_to='uploads/miniatures/'),
        ),
    ]
