# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-24 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='validation',
            field=models.IntegerField(default=0),
        ),
    ]
